import type { CodegenConfig } from "@graphql-codegen/cli";

/**
 * Schema source: the backend's committed `schema.gql` (code-first, generated by
 * NestJS/Apollo — see backend/CLAUDE.md), not live introspection against a running
 * dev server. More reliable for this workflow: codegen works without the backend
 * running, and can't drift from what's actually checked in.
 *
 * Re-run after any backend schema change: `npm run codegen` (or `codegen:watch`).
 */
const config: CodegenConfig = {
  schema: "../backend/src/schema.gql",
  documents: ["src/graphql/operations/**/*.graphql"],
  generates: {
    "src/graphql/generated.ts": {
      // No base "typescript" plugin: it would redeclare every input/enum type
      // typescript-operations already generates for the operations that use them
      // (CreateCommentInput, RootCommentSortField, SortOrder), producing duplicate
      // exports in this one shared file. typescript-operations is self-sufficient
      // for everything this app needs — the per-operation result/variable types
      // plus the handful of input/enum types they reference.
      plugins: ["typescript-operations", "typed-document-node"],
      config: {
        // The backend's DateTime scalar serializes as an ISO string over the wire.
        scalars: { DateTime: "string" },
      },
    },
  },
};

export default config;
